version: '3'

volumes:
  orderer2.example.com:

networks:
  fabric:
    external:
      name: fabric

services:
  orderer2:
    image: hyperledger/fabric-orderer:2.1
    #image: alpine
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG

      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp

      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      #- ORDERER_GENERAL_PROFILE_ENABLED=true
      #- ORDERER_GENERAL_PROFILE_ADDRESS=orderer.example.com:6065
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric ## orderer안붙임
    command: orderer 
    volumes:
    - /home/root/prj/fabric/fabric-samples-master/first-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - /home/root/prj/fabric/fabric-samples-master/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/:/var/hyperledger/orderer/msp/
    - /home/root/prj/fabric/fabric-samples-master/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls/
    - orderer2.example.com:/var/hyperledger/production/orderer
    deploy:
            replicas: 1
            placement:
              constraints: [node.hostname == node2]
    ports:
      - 8050:8050

    networks:
      fabric:
        aliases:
         - orderer2.example.com
